platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/kafka-zookeeper

inputs:
- name: git-http-gateway
- name: git-pfs-ci
- name: sk8s-version

outputs:
- name: docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |

    start_kafka

    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    SK8S_VERSION=$(determine_sk8s_version "$build_root/git-http-gateway" "$build_root/sk8s-version")

    export GOPATH=$(go env GOPATH)

    mkdir -p "$GOPATH/src/github.com/sk8sio"
    cp -pr git-http-gateway/ "$GOPATH/src/github.com/sk8sio/http-gateway"

    killjava() {
        set +e
        pkill -9 java
        set -e
    }
    trap killjava INT QUIT TERM EXIT

    pushd "$GOPATH/src/github.com/sk8sio/http-gateway/"

      make build-for-docker

      KAFKA_BROKER=localhost:9092 go test -v ./...

      killjava

      sed -i -e 's/scratch/alpine/g' Dockerfile

      ls -lath

      cp -pr . "$build_root/docker-context/"

      echo "$SK8S_VERSION" > "$build_root/docker-context/sk8s_version"

    popd
